import type { Metadata } from "next";

import HeaderLayout from "@/components/layout/HeaderLayout";
import './globals.css'

export const metadata: Metadata = {
  title:'Phantom of Linux',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <HeaderLayout>
          {children}
        </HeaderLayout>
      </body>
    </html>
  )
}