import type { Metadata } from "next";
import {Inter} from "next/font/google";

import HeaderLayout from "@/components/layout/HeaderLayout";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title:'Phantom of Linux',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderLayout>
          {children}
        </HeaderLayout>
      </body>
    </html>
  )
}