import { Suspense } from "react";

import type { Metadata } from "next";

import Loding from "./Loading";

import PageLayout from "@/components/layout/PageLayout";
import '../styles/globals.css'

export const metadata: Metadata = {
  title:'Phantom of Linux',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body>
        <PageLayout>
          <Suspense fallback={<Loding/>}>
          {children}
          </Suspense>
        </PageLayout>
      </body>
    </html>
  )
}